name: kkfish
version: 1.4.0
main: me.kkfish.kkfish
api-version: 1.13
description: Stardew Valley Style Fishing Plugin
author: gukuan
softdepend: [Vault, PlayerPoints, RealisticSeasons]

commands:
  kkfish:
    description: Main command
    aliases: [kf]
    permission: kkfish.use
    permission-message: "§dYou need {perm} permission to use this command"
permissions:
  kkfish.admin:
    description: Administrator permission
    default: op
  kkfish.user:
    description: User permission
    default: true
    children:
      kkfish.use: true
      kkfish.sell: true
  kkfish.use:
    description: Allow using basic fishing plugin features
    default: true
  kkfish.sell:
    description: Allow selling caught fish
    default: true
  # Hook Material Permissions
  kkfish.hook.*:
    description: Allow using all hook materials
    default: false